# Site settings
title: "Pensamientos y m√°s"
description: "El mundo de mi mente"
baseurl: ""
url: "http://pensamientos.kporras07.tk"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3

# Links
links:
  - title: "Inicio"
    url: /
  - title: "Acerca de"
    url: /acerca-de
  - title: "Twitter"
    url: http://twitter.com/kporras07
  - title: "Rss"
    url: /feed.xml
